apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    purpose: monitoring-logging
    security.kubernetes.io/level: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    purpose: persistent-storage
    security.kubernetes.io/level: restricted